const $=id=>document.getElementById(id),{defaults,calc,solve}=Pricing;
let state={...defaults},history=[],savedDefaults=null,recommendation=null,pendingImport=null;
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),jpy=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={productFields:[['name','商品名','','text','wide'],['sku','SKU','','text'],['category','商品区分','','select',[['shaft','シャフト'],['grip','グリップ'],['sleeve','スリーブ'],['head','ヘッド'],['club','完成クラブ']]],['quantity','セット数量','本 / 点','number',1],['cost','1 本・1 点あたりの仕入原価','JPY'],['pack','1 注文の梱包資材費','JPY'],['handling','1 注文の国内作業費','JPY'],['overhead','1 注文の固定費配賦','JPY'],['yahoo','国内参考価格（税抜）','JPY'],['origin','製造原産国','','text'],['hts','HTS 分類候補','','text']],saleFields:[['price','商品・セットの販売価格','USD'],['buyerShipping','購入者負担の送料','USD'],['tax','Sales Tax 想定税率','%'],['fx','基準為替レート','JPY / USD','number',.01],['fxFee','為替・出金コスト','%']],shippingFields:[['box','箱のサンプル','','select',[['A','箱 A'],['B','箱 B'],['custom','カスタム']]],['weight','梱包後の実重量','kg'],['length','長さ','cm'],['width','幅','cm'],['height','高さ','cm'],['divisor','容積重量の除数','cm³ / kg','number',1],['freight','基本送料（燃油別）','JPY'],['fuel','燃油サーチャージ','%'],['surcharge','遠隔地・長尺等の追加料金','JPY'],['duty','関税の合計想定税率','%'],['processing','通関処理費の想定料率','%'],['processingBase','処理費の計算基準','','select',[['duty','関税額（参考試算）'],['value','申告価格']]],['customsMode','申告価格の基準','','select',[['price','販売価格に連動（試算）'],['manual','確認済み価格を入力']]],['customsValue','手入力の申告価格','USD'],['importFixed','その他の輸入固定費・MPF','USD']],feeFields:[['fvf','落札手数料 FVF','%'],['threshold','FVF 第 1 区分の上限','USD'],['upper','上限超過分の料率','%'],['intl','海外決済手数料','%'],['ad','広告経由売上の広告料率','%'],['vat','手数料の消費税','%'],['buffer','概算モデルの合算手数料','%'],['returnRate','返品・損失発生率','%'],['returnLoss','1 件あたりの想定損失','JPY']]};
for(const [group,items] of Object.entries(groups))$(group).innerHTML=items.map(([id,label,unit,type='number',extra])=>`<label class="${extra==='wide'?'wide':''}" for="${id}">${label}<span class="unit">${unit}</span>${type==='select'?`<select id="${id}">${extra.map(o=>`<option value="${Array.isArray(o)?o[0]:o}">${Array.isArray(o)?o[1]:o}</option>`).join('')}</select>`:`<input id="${id}" type="${type}" ${type==='number'?`min="${typeof extra==='number'?extra:0}" step="${id==='quantity'?1:'any'}" ${['tax','fxFee','fvf','upper','intl','ad','vat','buffer','returnRate'].includes(id)?'max="100"':''}`:'maxlength="180"'}>`}</label>`).join('');
function sync(){for(const [k,v]of Object.entries(state))if($(k))$(k).value=v;}
function valid(){try{if([...document.querySelectorAll('input[type=number]')].some(e=>e.value===''||!e.checkValidity()))return false;PricingData.validateInputs(state);return true}catch{return false}}
function read(){for(const k of Object.keys(defaults))if($(k))state[k]=$(k).type==='number'?Number($(k).value):$(k).value;}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500);}
function row(label,value,cl=''){return `<div class="row ${cl}"><span>${label}</span><strong>${value}</strong></div>`}
function update(){read();let ok=valid();$('invalid').hidden=ok;for(const id of ['save','export','apply','saveDefaults','exportSettings','exportAll'])$(id).disabled=!ok;if(!ok){$('invalid').textContent='数値を確認してください。為替・容積重量の除数は 0 より大きく、数量は正の整数で入力してください。';$('profit').textContent='—';$('margin').textContent='—';$('perUnit').textContent='—';$('goalStatus').textContent='入力を確認してください';$('profitFill').style.width='0%';$('recommended').textContent='—';$('recommendedNote').textContent='';recommendation=null;$('breakdown').textContent='入力を修正すると再計算されます。';return;}
 const r=calc(state);$('profit').textContent=jpy(r.profit);$('profit').style.color=r.profit<0?'#ffbaa4':'var(--lime)';$('margin').textContent=`利益率 ${r.margin.toFixed(1)}%`;$('perUnit').textContent=`1 本あたり ${jpy(r.perUnit)}`;$('modelLabel').textContent=state.model==='consultant'?'参考モデル':state.plan==='starter'?'Starter · 個別':'Basic+ · 個別';
 const targetProfit=state.targetMode==='amount'?state.target:r.revenue*state.fx*state.target/100;const delta=r.profit-targetProfit;$('goalStatus').textContent=delta>=0?`目標を上回る額：${jpy(delta)}`:`目標まであと ${jpy(-delta)}`;$('profitFill').style.width=Math.min(100,Math.max(0,targetProfit?r.profit/targetProfit*100:100))+'%';
 recommendation=solve(state);$('recommended').textContent=recommendation===null?'算出できません':usd(recommendation);$('apply').disabled=recommendation===null;$('recommendedNote').textContent=recommendation===null?'現在の費用と目標の組み合わせでは、計算上限内に解がありません。':`購入者負担送料は ${usd(state.buyerShipping)} のまま。購入者の税抜合計は ${usd(recommendation+state.buyerShipping)}。`;
 $('weightNote').textContent=`容積重量 ${r.dimWeight.toFixed(2)} kg · 参考課金重量 ${r.chargeWeight.toFixed(2)} kg（配送会社の切り上げ前）。箱 A/B は参考値です。寸法変更では送料を自動更新しません。実際の基本送料と長尺料金を入力してください。`;
 $('customsValue').disabled=state.customsMode==='price';for(const id of ['fvf','threshold','upper','intl','ad','vat'])$(id).disabled=state.model==='consultant';$('buffer').disabled=state.model!=='consultant';
 $('breakdown').innerHTML=row('商品＋送料（税抜売上）',usd(r.revenue))+row('Sales Tax（プラットフォーム徴収・売上外）',usd(r.salesTax),'sub')+row('購入者の支払総額',usd(r.base),'total')+row(state.model==='consultant'?'概算モデルの合算手数料':'落札手数料 FVF',`−${usd(r.fvf)}`)+ (state.model==='detail'?row('注文ごとの固定手数料',`−${usd(r.order)}`)+row('海外決済手数料',`−${usd(r.intl)}`)+row('広告経由の販売手数料',`−${usd(r.ad)}`)+row('手数料の消費税（概算）',`−${usd(r.vat)}`):'')+row('プラットフォーム手数料控除後',usd(r.payout),'total')+row('為替・出金コスト',`−${usd(r.fxCost)}`)+row('関税（想定）',`−${usd(r.duty)}`)+row('通関処理費＋輸入固定費',`−${usd(r.processing+state.importFixed)}`)+row('配送コスト（燃油込み）',`−${jpy(r.shipping)}`)+row('物流・輸入費控除後の手取り',jpy(r.net),'total')+row('セット全体の仕入原価',`−${jpy(state.cost*state.quantity)}`)+row('梱包・作業・固定費配賦',`−${jpy(state.pack+state.handling+state.overhead)}`)+row('返品・損失の期待費用',`−${jpy(r.risk)}`)+row('予想利益',jpy(r.profit),'total');renderAnalysis();}
function presetPlan(){const basic=$('plan').value==='basic';$('fvf').value=basic?12.7:13.6;$('threshold').value=basic?2500:7500;$('upper').value=2.35;}
$('form').addEventListener('submit',e=>e.preventDefault());
$('form').addEventListener('input',e=>{if(e.target.id==='plan')presetPlan();if(e.target.id==='box'){const b=e.target.value;if(b!=='custom'){for(const[k,v]of Object.entries({length:119,width:10,height:b==='A'?5:10,freight:b==='A'?3691.25:4696.25,fuel:60}))$(k).value=v;}} update();});
for(const id of ['target','targetMode'])$(id).addEventListener('input',()=>{if(id==='targetMode')$('target').value=$('targetMode').value==='amount'?2000:20;update()});
$('apply').onclick=()=>{if(recommendation!==null){$('price').value=recommendation;update();toast('逆算した販売価格を適用しました')}};
$('reset').onclick=()=>{state={...defaults};sync();update();toast('Starter のサンプルに戻しました')};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));};
function renderAnalysis(){const s=state;let variants=[['現在の設定',s],['概算モデル',{...s,model:'consultant'}],['ストレステスト',{...s,fx:s.fx*.95,fuel:s.fuel+10,returnRate:Math.max(s.returnRate,3)}]];$('scenarios').innerHTML=variants.map(([n,x])=>{let r=calc(x);return `<article class="card scenario"><span class="source-tag">${n}</span><strong>${jpy(r.profit)}</strong><p>利益率 ${r.margin.toFixed(1)}% · 為替 ${x.fx.toFixed(2)}</p><p>${n==='ストレステスト'?'円換算レートを 5% 引き下げ、燃油を 10 ポイント加算、損失率を最低 3% に設定。':n==='概算モデル'?`合算料率 ${s.buffer}% で eBay 手数料・手数料消費税を置き換え、他の条件は維持。`:'現在の入力値をすべて使用。'}</p></article>`}).join('');let values=[-10,-5,0,5,10].map(d=>({fx:s.fx+d,r:calc({...s,fx:Math.max(.01,s.fx+d)})})).filter(x=>x.fx>0),max=Math.max(...values.map(x=>Math.abs(x.r.profit)),1);$('fxChart').innerHTML=values.map(x=>`<div class="barrow"><span>¥${x.fx.toFixed(0)}</span><span class="bar"><i style="width:${Math.abs(x.r.profit)/max*100}%;background:${x.r.profit<0?'#bf765d':'#4c846c'}"></i></span><b>${jpy(x.r.profit)}</b></div>`).join('');
 let a=calc({...s,model:'detail',fvf:13.6,threshold:7500,upper:2.35}),b=calc({...s,model:'detail',fvf:12.7,threshold:2500,upper:2.35});let annual=$('billing').value==='year',starter=annual?4.95:7.95,basic=annual?21.95:27.95,diff=(basic-starter)*(1+s.vat/100),saving=(a.fees-b.fees),orders=+$('monthlyOrders').value; $('storeCompare').innerHTML=row('Starter / Basic 月額（税抜）',`${usd(starter)} / ${usd(basic)}`)+row('1 注文あたりの削減額',usd(saving))+row('月額差を回収する注文数',saving>0?Math.ceil(diff/saving)+' 件 / 月':'差額を回収できません','total')+row('月額差を引いた月間削減額',Number.isFinite(orders)&&orders>=1?usd(orders*saving-diff):'注文数を確認してください');
 $('shippingTable').innerHTML=[29.99,49.99,99.99,199.99,299.99].map(price=>{let shipping=solve({...s,price},'buyerShipping'),r=shipping===null?null:calc({...s,price,buyerShipping:shipping});return `<tr><td>${usd(price)}</td><td>${r?usd(shipping):'算出できません'}</td><td>${r?usd(price+shipping):'—'}</td><td>${r?jpy(r.profit):'—'}</td></tr>`}).join('');}
for(const id of ['billing','monthlyOrders'])$(id).addEventListener('input',update);
const sources=[
 ['公式','eBay 落札手数料・ストアプラン','Starter は通常 13.6%（$7,500 まで）、超過分は 2.35%。Basic 以上の Sporting Goods は 12.7%（$2,500 まで）、超過分は 2.35%。注文固定費は $10 以下が $0.30、超える場合は $0.40。','https://www.ebay.com/help/selling/fees-credits-invoices/store-selling-fees?id=4809'],
 ['公式','日本の海外決済手数料','標準 1.35%。売上額やセラーレベル等の条件を満たす場合は割引があります。前月売上 $3,000 / $10,000 / $50,000 / $100,000 の区分に対応して 1.20 / 0.95 / 0.70 / 0.40%。適用率はアカウントで確認してください。','https://www.ebay.com/help/selling/fees-credits-invoices/selling-fees?id=5224'],
 ['公式','General 広告費','広告経由の売上に対して、入力した広告料率が適用される場合を試算します。広告を利用しない場合は 0 を入力。商品・送料・税を計算基準に含みます。Priority のクリック課金は対象外です。','https://www.ebay.com/help/selling/listings/optimizing-your-listings?id=4164'],
 ['公式','手数料にかかる日本の消費税','初期値は 10% の支出として計算します。Tax Invoice の課税対象額に合わせて調整してください。仕入税額控除は自動反映しません。','https://www2.ebay.co.jp/knowledge/shipping/article74'],
 ['公式','米国の関税制度変更','CBP は対象となる IEEPA 追加関税の徴収を 2026-02-24 から終了すると通知しています。他の税負担がなくなることを意味しません。過去の対日追加税率を現行の総税率として固定していません。','https://content.govdelivery.com/accounts/USDHSCBP/bulletins/40b11c9'],
 ['公式','HTS 品目分類','9506.39.0060 はゴルフクラブ部品の分類候補です。シャフト・グリップ・ヘッド・完成クラブはそれぞれ確認してください。商品区分を変更しても税率は自動変更されません。','https://hts.usitc.gov/'],
 ['公式','米国向け DDP','従来の $800 以下の一律免税を前提にしないでください。eBay 日本は 2025-10-17 から米国向け $2,500 未満の取引で DDP を必須としています。最新の配送・通関条件を確認してください。','https://www.ebay.co.jp/ddp-info'],
 ['公式','MPF と配送会社の処理費','正式通関の MPF は 0.3464% で、年度ごとに下限・上限があります。簡易通関には別の規則があります。参考値の 2.1% は公式 MPF ではありません。適用される固定費を入力し、送料との二重計上を避けてください。','https://www.help.cbp.gov/s/article/Article-1128?language=en_US'],
 ['参考試算','コンサルタントのモデル','合算手数料 20%、関税 12.5%、関税額の 2.1% の処理費、燃油 60%、¥150/USD は参考条件です。箱 A ¥5,906・箱 B ¥7,514 は燃油込みの例のため、基本送料に分解して計算します。',null],
 ['サンプル','原価・為替・物流','仕入 ¥4,000、梱包 ¥150、作業 ¥100 はサンプルです。国内参考価格を仕入原価として計算しません。容積重量の除数 5,000 は仮定で、配送サービスごとの確認が必要です。',null]
];
$('sourceList').innerHTML=sources.map(([type,title,body,url])=>`<article class="card"><span class="source-tag ${type==='公式'?'':'estimate'}">${type}</span><h2>${title}</h2><p>${body}</p>${url?`<a href="${url}" target="_blank" rel="noopener">公式資料を見る ↗</a>`:'<span class="note">編集可能な参考条件</span>'}</article>`).join('');
// One atomic storage entry, scoped to this deployment path on a shared GitHub Pages origin.
const pathScope=new URL('.',location.href).pathname;
const STORAGE_KEY='golf-export-lab:v2:'+pathScope;
let storageWarning='';
function status(){ $('storageStatus').textContent=storageWarning||'保存先：このブラウザ（localStorage）。移行・バックアップは「保存・入出力」から。'; }
function storeBundle(nextState,nextDefaults,nextHistory){
 try{const doc=PricingData.documentData(nextState,nextDefaults,nextHistory);const text=JSON.stringify(doc);if(new TextEncoder().encode(text).length>PricingData.MAX_BYTES)throw new Error('容量制限');localStorage.setItem(STORAGE_KEY,text);storageWarning='';status();return true}
 catch(e){storageWarning='保存できませんでした。ブラウザの保存制限・空き容量を確認し、JSON でバックアップしてください。';status();toast(storageWarning);return false}
}
function loadBundle(){
 try{const text=localStorage.getItem(STORAGE_KEY);if(text){const data=PricingData.parse(text);history=data.history;savedDefaults=data.savedDefaults;state={...(savedDefaults||defaults)};}}
 catch(e){storageWarning='保存データを読み込めませんでした。保存内容は上書きしていません。JSON のバックアップから復元できます。';}
 status();
}
function snapshot(){return {id:typeof crypto.randomUUID==='function'?crypto.randomUUID():'s-'+Date.now()+'-'+Math.random().toString(36).slice(2),engineVersion:'1.1',checked:'2026-09-28',at:new Date().toISOString(),inputs:{...state},result:calc(state)}}
function renderHistory(){
 $('historyCount').textContent=history.length;
 $('historyList').innerHTML=history.length?history.map((h,i)=>`<article class="card historycard"><div><h2>${esc(h.inputs.name)}</h2><p>${esc(new Date(h.at).toLocaleString('ja-JP'))} · ${h.inputs.plan==='basic'?'Basic 以上':'Starter'} · ${usd(h.inputs.price)} · 利益 ${jpy(h.result.profit)}</p></div><div class="actions"><button data-restore="${i}">この試算を開く</button><button data-download="${i}">CSV を出力</button><button data-delete="${i}">削除</button></div></article>`).join(''):'<div class="card"><h2>保存した試算はありません</h2><p class="note">「試算を履歴に保存」で、その時点の条件を残せます。</p></div>';
}
$('save').onclick=()=>{if(!valid())return;if(history.length>=PricingData.MAX_HISTORY){toast('履歴は最大 500 件です。バックアップ後に不要な履歴を削除してください。');return}const next=[snapshot(),...history];if(storeBundle(state,savedDefaults,next)){history=next;renderHistory();toast('試算をこのブラウザに保存しました')}};
$('saveDefaults').onclick=()=>{if(valid()&&storeBundle(state,state,history)){savedDefaults={...state};toast('次回の既定設定を保存しました')}};
$('loadDefaults').onclick=()=>{if(!savedDefaults){toast('既定設定はまだ保存されていません');return}state={...savedDefaults};sync();update();document.querySelector('[data-tab="calculator"]').click();toast('保存済みの設定を適用しました')};
$('historyList').onclick=e=>{let b=e.target.closest('button');if(!b)return;
 if(b.dataset.restore!==undefined){state={...history[+b.dataset.restore].inputs};sync();update();document.querySelector('[data-tab="calculator"]').click();toast('保存した試算を開きました')}
 if(b.dataset.download!==undefined)downloadCSV(history[+b.dataset.download]);
 if(b.dataset.delete!==undefined){if(!confirm('この試算を削除しますか？削除後に戻すには JSON バックアップが必要です。'))return;const next=history.filter((_,i)=>i!==+b.dataset.delete);if(storeBundle(state,savedDefaults,next)){history=next;renderHistory();toast('試算を削除しました')}}
};
function saveFile(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const inputLabels=Object.fromEntries(Object.values(groups).flat().map(x=>[x[0],x[1]]));Object.assign(inputLabels,{model:'計算モデル',plan:'ストアプラン',target:'目標値',targetMode:'目標の指定方法',billing:'契約期間',monthlyOrders:'月間注文数'});
const resultLabels={revenue:'税抜売上（USD）',salesTax:'Sales Tax（USD）',base:'購入者支払額（USD）',fvf:'落札手数料（USD）',order:'注文固定費（USD）',intl:'海外決済手数料（USD）',ad:'広告費（USD）',vat:'手数料消費税（USD）',fees:'プラットフォーム手数料合計（USD）',payout:'プラットフォーム手数料控除後（USD）',fxCost:'為替・出金コスト（USD）',duty:'関税（USD）',processing:'処理費（USD）',imports:'輸入費用（USD）',shipping:'配送費（JPY）',net:'物流・輸入費控除後の手取り（JPY）',cost:'原価等（JPY）',risk:'想定損失（JPY）',profit:'利益（JPY）',margin:'利益率（%）',perUnit:'1 本・1 点の利益（JPY）',dimWeight:'容積重量（kg）',chargeWeight:'参考課金重量（kg）'};
function downloadCSV(h){const rows=[['区分','項目','値'],['情報','計算バージョン',h.engineVersion],['情報','確認日',h.checked],['情報','保存日時',h.at],...Object.entries(h.inputs).map(([k,v])=>['入力',inputLabels[k]||k,v]),...Object.entries(h.result).map(([k,v])=>['結果',resultLabels[k]||k,v]),...sources.map(([a,b,c,d])=>['出典',b,`${a}: ${c} ${d||''}`])];const safe=v=>{let t=String(v);if(/^[\s]*[=+@]/.test(t)||(/^[\s]*-/.test(t)&&!Number.isFinite(Number(t))))t="'"+t;return '"'+t.replace(/"/g,'""')+'"'};saveFile('\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n'),'golf-pricing-'+h.at.slice(0,10)+'.csv','text/csv;charset=utf-8')}
$('export').onclick=()=>{if(valid())downloadCSV(snapshot())};
function exportJSON(kind){if(!valid()){toast('書き出す前に入力値を確認してください');return}const data=PricingData.documentData(state,savedDefaults,history,kind);saveFile(JSON.stringify(data),'golf-export-'+kind+'-'+new Date().toISOString().slice(0,10)+'.json','application/json')}
$('exportSettings').onclick=()=>exportJSON('settings');$('exportAll').onclick=()=>exportJSON('backup');
$('importButton').onclick=()=>{$('importFile').value='';$('importFile').click()};
$('importFile').onchange=async e=>{
 $('importError').textContent='';pendingImport=null;const file=e.target.files[0];if(!file)return;
 try{if(file.size>PricingData.MAX_BYTES)throw new Error('ファイルは 2 MB 以下にしてください。');const data=PricingData.parse(await file.text());PricingData.mergeHistory(history,data.history);pendingImport=data;
 $('importSummary').textContent=`${data.kind==='settings'?'設定ファイル':'バックアップ'} / 書き出し：${new Date(data.exportedAt).toLocaleString('ja-JP')} / 商品：${data.current.name} / プラン：${data.current.plan==='basic'?'Basic 以上':'Starter'} / 履歴：${data.history.length} 件。`;
 $('importDefaultMode').value='keep';$('importDefaultMode').querySelector('[value=saved]').disabled=data.savedDefaults===null;$('importDialog').showModal();
 }catch(err){$('importError').textContent=err.message+' 既存データは変更していません。'}
};
$('cancelImport').onclick=()=>{pendingImport=null;$('importDialog').close()};$('importDialog').addEventListener('cancel',()=>pendingImport=null);
$('confirmImport').onclick=()=>{if(!pendingImport)return;try{const data=pendingImport,nextHistory=PricingData.mergeHistory(history,data.history),nextDefaults=$('importDefaultMode').value==='current'?{...data.current}:$('importDefaultMode').value==='saved'?data.savedDefaults:savedDefaults;
 if(!storeBundle(data.current,nextDefaults,nextHistory))return;state={...data.current};history=nextHistory;savedDefaults=nextDefaults;pendingImport=null;$('importDialog').close();sync();update();renderHistory();document.querySelector('[data-tab="calculator"]').click();toast('設定と履歴を読み込みました');
 }catch(e){$('importDialog').close();pendingImport=null;$('importError').textContent=e.message;}};
loadBundle();sync();update();renderHistory();
const mc=document.modelContext;if(mc?.registerTool){try{Promise.resolve(mc.registerTool({name:'read_pricing_simulation',description:'現在のゴルフ用品の価格試算と入力条件を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('引数は指定できません');if(!valid())throw new Error('入力値を確認してください');return snapshot()}})).catch(()=>{});}catch{}}
