'use strict';
const $=id=>document.getElementById(id),P=Pricing,D=PricingData,R=RateUpdates;
const usd=x=>x===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(x),jpy=x=>x===null?'未計算':new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
let settings={...P.common},state=P.blank(),boxes=[],history=[],updates={...R.defaults,logs:[]},recommendation=null,lastResult=null,pendingImport=null,editingBox=null,confirmCallback=null,rateBusy=false,revision=0,storageUnreadable=false;
const storageKey='golf-export-lab:v3:'+new URL('.',location.href).pathname,legacyKey='golf-export-lab:v2:'+new URL('.',location.href).pathname;
// [key, Japanese label, unit, select options or text type]. All numbers allow a blank draft.
const groups={
 identityFields:[['name','商品名','','text'],['category','商品種類','',[['','選択してください'],['shaft','シャフト'],['grip','グリップ'],['sleeve','スリーブ'],['head','ヘッド'],['club','完成クラブ']]]],
 sourceFields:[['pricingSource','基準にする価格','',[['wholesale','問屋の仕入価格'],['rakuten','楽天市場の商品価格'],['yahoo','Yahoo!ショッピングの商品価格']]]],
 marketInputs:[['referencePrice','日本の商品価格（1 本・1 点）','JPY']],
 pricingDefaults:[['quantity','通常の販売数量','本 / 点'],['marketUsage','楽天・Yahoo! 価格の使い方','',[['reference','日本の販売価格を保つ'],['purchase','購入する金額として使う']]],['referenceTaxMode','日本価格の税金','',[['gross','税込価格'],['net','税抜価格']]],['referenceTax','日本の消費税率','%'],['referenceUplift','日本価格に追加する余裕（任意）','%'],['referenceExtras','日本価格に梱包・作業・想定損失を加算','',[['include','加算して回収する'],['ignore','日本価格だけを回収する']]]],
 costFields:[['cost','仕入原価（1 本・1 点）','JPY']],
 targetFields:[['targetMode','目標の指定方法','',[['amount','1 注文の利益額'],['margin','売上に対する利益率']]],['target','目標利益','JPY / %']],
 deliveryFields:[['freight','配送会社に払う基本送料','JPY'],['buyerShipping','購入者に請求する送料','USD'],['fx','1 USD は何円か','JPY'],['weight','梱包後の重さ（任意）','kg']],
 shippingFields:[['fuel','燃油サーチャージ','%'],['surcharge','遠隔地・長尺などの追加送料','JPY'],['pack','梱包資材費','JPY'],['length','箱の長さ','cm'],['width','箱の幅','cm'],['height','箱の高さ','cm'],['divisor','容積重量の除数','']],
 priceFields:[['price','eBay の商品価格（セット全体）','USD']],
 extraFields:[['sku','管理番号 / SKU','','text'],['origin','製造された国','','text'],['hts','HTS コード（品目分類）','','text'],['customsValue','手入力の申告価格','USD'],['referenceURL','参考にした商品 URL','','text']],
 modelFields:[['plan','eBay ストアプラン','',[['starter','Starter / ストアなし'],['basic','Basic 以上']]],['model','費用の計算方法','',[['detail','内訳から計算（通常はこちら）'],['consultant','まとめて概算（比較用）']]]],
 feeFields:[['fvf','落札手数料（FVF）','%'],['intl','海外決済手数料','%'],['ad','広告経由の注文の広告料率','%'],['vat','手数料にかかる日本の消費税','%'],['fxFee','為替・出金手数料','%'],['buffer','まとめて概算する料率','%']],
 advancedFeeFields:[['threshold','FVF 第 1 区分の上限','USD'],['upper','上限を超えた分の FVF','%'],['orderThreshold','注文固定費が変わる金額','USD'],['orderLow','小額注文の固定費','USD'],['orderHigh','通常注文の固定費','USD'],['billing','ストアの契約期間','',[['year','年間契約'],['month','月間契約']]],['monthlyOrders','比較に使う月間注文数','件'],['starterYear','Starter 年間契約の月額','USD'],['basicYear','Basic 年間契約の月額','USD'],['starterMonth','Starter 月間契約の月額','USD'],['basicMonth','Basic 月間契約の月額','USD']],
 importFields:[['duty','米国の関税率（要確認）','%'],['processing','通関処理費の料率','%'],['processingBase','通関処理費をかける対象','',[['duty','関税の金額'],['value','申告価格']]],['importFixed','その他の輸入固定費・MPF','USD'],['customsMode','関税計算に使う価格','',[['price','商品価格だけ'],['total','商品価格＋購入者負担送料'],['manual','確認した申告価格を手入力']]],['tax','購入者の Sales Tax 想定率','%']],
 riskFields:[['handling','1 注文の国内作業費','JPY'],['overhead','1 注文の固定費の配分','JPY'],['returnRate','返品・損失が発生する割合','%'],['returnLoss','返品・損失 1 件あたりの金額','JPY']]
};
const labels=Object.fromEntries(Object.values(groups).flat().map(x=>[x[0],x[1]]));
function field([key,label,unit,options],prefix='',data=true){const id=prefix+key,isSelect=Array.isArray(options),text=options==='text';return `<label for="${id}" class="${text?'wide':''}">${esc(label)}${unit?`<span class="unit">${unit}</span>`:''}${isSelect?`<select id="${id}" ${data?'data-state':''}>${options.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select>`:`<input id="${id}" ${data?'data-state':''} type="${text?'text':'number'}" ${text?'maxlength="300"':`min="${['quantity','monthlyOrders','divisor'].includes(key)?1:key==='fx'?.01:0}" step="${['quantity','monthlyOrders'].includes(key)?1:'any'}"`} >`}</label>`}
for(const [id,rows]of Object.entries(groups))$(id).innerHTML=rows.map(x=>field(x)).join('');
const boxFields=[['name','箱・配送の名前','','text'],['carrier','配送サービス','',[['','未選択'],['speedpak-fedex','SpeedPAK via FedEx'],['speedpak-dhl','SpeedPAK via DHL'],['other','その他']]],['length','長さ','cm'],['width','幅','cm'],['height','高さ','cm'],['weight','標準の梱包後重量','kg'],['divisor','容積重量の除数',''],['freight','基本送料（燃油別）','JPY'],['fuel','燃油サーチャージ','%'],['surcharge','長尺・遠隔地などの追加送料','JPY'],['pack','梱包資材費','JPY'],['rateKey','自動更新用の運費キー（任意）','','text']];
$('boxFields').innerHTML=boxFields.map(x=>field(x,'box_',false)).join('');
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4500)}
function switchTab(id){document.querySelectorAll('.tab').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===id));}
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>switchTab(button.dataset.tab);for(const button of document.querySelectorAll('[data-open]'))button.onclick=()=>switchTab(button.dataset.open);
function sync(){for(const el of document.querySelectorAll('[data-state]'))el.value=state[el.id]??'';renderBoxes();$('fxMode').value=updates.fxMode;$('shippingFeed').value=updates.shippingUrl;}
function read(){for(const el of document.querySelectorAll('[data-state]'))state[el.id]=el.type==='number'?(el.value===''?null:Number(el.value)):el.value;}
function commonFromState(){return D.validateSettings(Object.fromEntries(Object.keys(P.common).map(k=>[k,state[k]])))}
function validDraft(){try{D.validateInputs(state);return true}catch{return false}}
function localSave(next={}){const ns=next.settings??settings,nb=next.boxes??boxes,nh=next.history??history,nu=next.updates??updates;try{const data=D.documentData(P.blank(ns),ns,nb,nh,'backup',nu),text=JSON.stringify(data);if(new TextEncoder().encode(text).length>D.MAX_BYTES)throw new Error('保存容量を超えています。');localStorage.setItem(storageKey,text);$('storageStatus').textContent='設定・履歴はこのブラウザに保存します。';return true}catch(e){$('storageStatus').textContent='保存できませんでした。JSON でバックアップしてください。';toast(e.message||'ブラウザの保存設定を確認してください。');return false}}
function confirmAction(text,action){$('confirmText').textContent=text;confirmCallback=action;$('confirmDialog').showModal()}
$('cancelAction').onclick=()=>{$('confirmDialog').close();confirmCallback=null};$('confirmAction').onclick=()=>{const action=confirmCallback;confirmCallback=null;$('confirmDialog').close();action?.()};
function row(label,value,cls=''){return `<div class="row ${cls}"><span>${esc(label)}</span><strong>${value}</strong></div>`}
function resultCSVLabels(){return {revenue:'税抜売上 USD',salesTax:'Sales Tax USD',base:'購入者支払 USD',fvf:'FVF USD',order:'注文固定費 USD',intl:'海外決済手数料 USD',ad:'広告費 USD',vat:'手数料消費税 USD',fees:'プラットフォーム手数料合計 USD',payout:'プラットフォーム手数料控除後 USD',fxCost:'為替・出金費 USD',duty:'関税 USD',processing:'通関処理費 USD',imports:'輸入費用合計 USD',shipping:'配送コスト JPY',net:'物流・輸入費控除後 JPY',cost:'仕入・作業等 JPY',risk:'想定損失 JPY',profit:'利益 JPY',margin:'利益率 %',perUnit:'1 本あたり利益 JPY',dimWeight:'容積重量 kg',chargeWeight:'課金参考重量 kg'}}
function render(){
 const market=state.pricingSource!=='wholesale',reference=market&&state.marketUsage==='reference',purchase=market&&state.marketUsage==='purchase';
 $('marketFields').hidden=!market;$('costFields').hidden=purchase; $('costHelp').hidden=market;
 if(market)$('optionalCost').appendChild($('costFields'));else $('costHelp').before($('costFields'));
 $('targetFields').hidden=false;
 $('marketHelp').textContent=reference?'この日本価格には、すでに必要な利益が含まれている前提です。同じ売上を残せる eBay 価格を逆算します。':'ここで購入して販売する場合は、税込購入額を仕入原価として使います。';
 $('costHelp').textContent=reference?'実際の仕入原価は任意です。入力すると利益も確認できます。日本の販売価格を仕入原価として扱うことはありません。':purchase?'楽天・Yahoo! の税込価格を仕入原価として計算します。':'実際に仕入先へ支払う金額を入力してください。';
 $('customsValue').disabled=state.customsMode!=='manual';for(const k of ['referenceUplift','referenceExtras'])$(k).disabled=!reference;
 $('buffer').disabled=state.model!=='consultant';for(const k of ['fvf','intl','ad','vat','threshold','upper','orderLow','orderHigh','orderThreshold'])$(k).disabled=state.model==='consultant';
 $('recommendTitle').textContent=reference?'同じ収益を残す eBay おすすめ価格':'目標利益を含む eBay おすすめ価格';
 const ref=P.reference(state);$('referenceSummary').innerHTML=ref?row('税抜の日本価格（1 点）',jpy(ref.net))+(reference?row('この注文で残す目標額',state.quantity===null?'数量を入力':jpy(ref.recovery))+`<p class="help">${state.referenceExtras==='include'?'梱包・作業・想定損失などの追加費用も目標額に含めます。':'追加費用を上乗せせず、日本価格だけを回収します。'}仕入原価を引く前の金額です。</p>`:row('税込の購入原価（1 点）',jpy(ref.gross))):'';
 let error='';try{D.validateInputs(state)}catch(e){error=e.message}
 const recommendIssues=P.issues(state,'recommend');
 recommendation=!error&&!recommendIssues.length?P.recommend(state):null;
 state.price=recommendation;$('price').value=recommendation??'';const forwardIssues=P.issues(state,'forward');
 $('recommended').textContent=recommendation===null?'—':usd(recommendation);$('apply').disabled=recommendation===null;
 $('recommendHint').textContent=error|| (recommendIssues.length?'未入力：'+recommendIssues.join('・')+'。配送・税金・利益の条件は設定で保存できます。':recommendation===null?'この条件では目標に届きません。費用や目標を見直してください。':`購入者に請求する送料 ${usd(state.buyerShipping)} は別。税抜合計 ${usd(recommendation+state.buyerShipping)}。`);
 $('inputIssues').innerHTML=state.duty===null?'関税率が未入力です。<button class="link-button" id="dutyLink">設定で入力する</button>':'';$('dutyLink')?.addEventListener('click',()=>{switchTab('settings');$('duty').focus()});
 lastResult=!error&&!forwardIssues.length?P.calc(state):null;
 $('saveHistory').disabled=!lastResult;$('exportCSV').disabled=!lastResult;
 for(const k of ['buyerTotal','net','profit','margin','effectiveRate'])$(k).textContent='—';
 $('breakdown').innerHTML='<p class="empty">商品価格と必要な条件を入力すると表示します。</p>';
 $('feeBreakdown').innerHTML='<p class="help">価格を入力すると、この注文の費用を 1 項目ずつ計算します。</p>';
 $('feeCompare').textContent='20% は粗い目安です。通常は内訳を積み上げて計算します。';
 $('resultHelp').textContent=error|| (forwardIssues.length?'商品価格を入力し、未入力の計算条件を設定すると明細を表示します。':'');
 if(lastResult){const r=lastResult;$('buyerTotal').textContent=usd(r.base);$('net').textContent=jpy(r.net);$('profit').textContent=r.profit===null?'原価未入力':jpy(r.profit);$('margin').textContent=r.profit===null?'—':`${r.margin.toFixed(1)}% / ${jpy(r.perUnit)}`;
 $('resultHelp').textContent=r.profit===null?'仕入原価を入力すると、原価・梱包・作業費などを引いた利益も表示できます。':'利益は、仕入・梱包・作業費・想定損失を引いた金額です。所得税等は含みません。';
 const detailed=P.calc({...state,model:'detail'}),combined=P.calc({...state,model:'consultant',buffer:state.buffer??20});
 const effective=r.revenue?(r.fees+r.fxCost)/r.revenue*100:0;
 $('effectiveRate').textContent=r.revenue?effective.toFixed(2)+'%':'—';
 $('feeBreakdown').innerHTML=(state.model==='detail'?row(`落札手数料（FVF ${state.fvf}%・上限超過は別率）`,usd(r.fvf))+row(`海外決済手数料 ${state.intl}%`,usd(r.intl))+row(`広告費 ${state.ad??0}%`,usd(r.ad))+row('注文ごとの固定費',usd(r.order))+row(`手数料の消費税 ${state.vat}%`,usd(r.vat)):row(`まとめて概算 ${state.buffer}%`,usd(r.fvf)))+row(`為替・出金費 ${state.fxFee??0}%`,usd(r.fxCost))+row('販売・決済費用の合計',usd(r.fees+r.fxCost),'total');
 $('feeCompare').textContent=r.revenue?`内訳で計算した場合は ${((detailed.fees+detailed.fxCost)/r.revenue*100).toFixed(2)}%。${state.buffer??20}% の合算モデルと比べると、この注文の費用は ${usd(Math.abs((detailed.fees+detailed.fxCost)-(combined.fees+combined.fxCost)))} ${detailed.fees+detailed.fxCost>=combined.fees+combined.fxCost?'高く':'安く'}なります。どちらも入力条件からの試算です。`:'割合を出すには売上を入力してください。';
 $('breakdown').innerHTML=row('適用為替',`1 USD = ${state.fx} JPY`)+(reference?row('日本の税抜価格（注文全体）',jpy(ref.net*state.quantity)): '')+row('商品代金',usd(state.price))+row('購入者負担送料',usd(state.buyerShipping))+row('Sales Tax（売上には含めない）',usd(r.salesTax),'sub')+row('購入者支払総額',usd(r.base),'total')+row('eBay 手数料・手数料消費税',`−${usd(r.fees)}`)+row('プラットフォーム手数料控除後',usd(r.payout),'total')+row('為替・出金費',`−${usd(r.fxCost)}`)+row('関税',`−${usd(r.duty)}`)+row('通関処理費・輸入固定費',`−${usd(r.processing+(state.importFixed??0))}`)+row('配送費（燃油・追加送料込み）',`−${jpy(r.shipping)}`)+row('物流・輸入費控除後の残額',jpy(r.net),'total')+row('仕入原価（注文全体）',P.effectiveCost(state)===null?'未入力':`−${jpy(P.effectiveCost(state)*state.quantity)}`)+row('梱包・作業・固定費',`−${jpy((state.pack??0)+(state.handling??0)+(state.overhead??0))}`)+row('返品等の想定損失',`−${jpy(r.risk)}`)+row('利益',jpy(r.profit),'total');
 }
 const dim=state.length&&state.width&&state.height&&state.divisor?state.length*state.width*state.height/state.divisor:null;
 $('weightNote').textContent=dim===null?'寸法と除数を入れると容積重量を計算します。送料は別途入力が必要です。':`容積重量 ${dim.toFixed(2)} kg${state.weight!==null?' / 課金参考重量 '+Math.max(dim,state.weight).toFixed(2)+' kg':''}。配送会社ごとの切り上げや長尺料金は別途確認してください。`;
 renderAnalysis();renderRateStatus();
}
function update(event){read();revision++;if(event?.target.id==='fx'){updates.fxMode='manual';updates.manualFx=state.fx;state.fxSource='手入力';state.fxDate='';$('fxMode').value='manual';}
 if(event?.target.id==='plan'){const basic=state.plan==='basic';state.fvf=basic?12.7:13.6;state.threshold=basic?2500:7500;state.upper=2.35;for(const k of ['fvf','threshold','upper'])$(k).value=state[k]}
 if(event&&['freight','fuel','surcharge','length','width','height','weight','divisor'].includes(event.target.id)){state.shippingSource='手入力';state.shippingDate='';}
 render();}
for(const id of ['productForm','settingsForm']){$(id).addEventListener('submit',e=>e.preventDefault());$(id).addEventListener('input',update)}
$('apply').onclick=()=>{if(recommendation===null)return;state.price=recommendation;$('price').value=state.price;render();toast('商品価格を適用しました')};
$('saveSettings').onclick=()=>{read();try{const next=commonFromState(),nu=R.validate({...updates,fxMode:$('fxMode').value,shippingUrl:$('shippingFeed').value.trim(),manualFx:$('fxMode').value==='manual'?state.fx:updates.manualFx});if(nu.shippingUrl)R.url(nu.shippingUrl,location.href);if(nu.shippingUrl!==updates.shippingUrl)nu.shippingCheckedDay='';if(localSave({settings:next,updates:nu})){settings=next;updates=nu;revision++;toast('税金・配送・為替・利益の設定を保存しました')}}catch(e){toast(e.message)}};
$('clear').onclick=()=>confirmAction('商品欄を空にします。共通設定・登録した箱・保存履歴は残ります。',()=>{state=P.blank(settings);applySavedFX();revision++;sync();render()});
$('sample').onclick=()=>confirmAction('現在の入力をサンプルに置き換えます。登録済みの箱や保存履歴は消しません。',()=>{const sampleBoxes=[{id:'sample-box-a',carrier:'',name:'入力例：箱 A',length:119,width:10,height:5,weight:.5,divisor:5000,freight:3691.25,fuel:60,surcharge:0,pack:150,rateKey:'',rateDate:'',rateSource:'参考試算'},{id:'sample-box-b',carrier:'',name:'入力例：箱 B',length:119,width:10,height:10,weight:.8,divisor:5000,freight:4696.25,fuel:60,surcharge:0,pack:150,rateKey:'',rateDate:'',rateSource:'参考試算'}];boxes=D.mergeBoxes(boxes,sampleBoxes);state=P.sample();state.fxSource='入力例（実勢レートではありません）';revision++;sync();render();toast('入力例を表示しました。設定は保存するまで変更されません。')});
function renderBoxes(){const selected=state.boxId;$('boxSelect').innerHTML='<option value="">選ばずに直接入力</option>'+boxes.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');$('boxSelect').value=boxes.some(b=>b.id===selected)?selected:'';
 $('boxList').innerHTML=boxes.length?boxes.map(b=>`<article class="box-item"><div><h3>${esc(b.name)}</h3><p>${b.length} × ${b.width} × ${b.height} cm / 基本送料 ${b.freight===null?'未入力':jpy(b.freight)}</p><p>${b.rateDate?'運費データ '+esc(b.rateDate):'運費は手動設定'}</p></div><div class="actions"><button data-edit-box="${esc(b.id)}">編集</button><button data-delete-box="${esc(b.id)}">削除</button></div></article>`).join(''):'<p class="empty">箱はまだ登録されていません。「新しく登録」から追加してください。</p>';
 const box=boxes.find(b=>b.id===state.boxId);$('boxSummary').textContent=box?`${box.name}：${state.length} × ${state.width} × ${state.height} cm。下の金額は今回だけ変更できます。`:'よく使う箱は「設定」で登録できます。';}
function selectBox(box){state.boxId=box.id;for(const k of ['length','width','height','weight','divisor','freight','fuel','surcharge','pack'])state[k]=box[k];state.shippingSource=box.rateSource||'登録した箱';state.shippingDate=box.rateDate||'';}
$('boxSelect').onchange=()=>{const box=boxes.find(b=>b.id===$('boxSelect').value);if(box)selectBox(box);else state.boxId='';revision++;sync();render()};
function openBox(box=null){editingBox=box?.id||null;$('boxForm').hidden=false;$('boxFormTitle').textContent=box?'箱・配送設定を編集':'箱・配送設定を登録';$('boxError').textContent='';for(const [key]of boxFields)$('box_'+key).value=box?.[key]??'';$('box_name').focus()}
$('newBox').onclick=()=>openBox();$('cancelBox').onclick=()=>{$('boxForm').hidden=true;editingBox=null};
$('boxForm').onsubmit=e=>{e.preventDefault();try{const previous=boxes.find(b=>b.id===editingBox),box={id:editingBox||uid(),rateDate:'',rateSource:'手入力'};for(const [k,,,type]of boxFields)box[k]=type==='text'||Array.isArray(type)?$('box_'+k).value:$('box_'+k).value===''?null:Number($('box_'+k).value);D.validateBox(box);if(!editingBox&&boxes.length>=D.MAX_BOXES)throw new Error('箱は 100 件まで登録できます。');const next=editingBox?boxes.map(b=>b.id===editingBox?box:b):[...boxes,box];if(localSave({boxes:next})){boxes=next;if(state.boxId===box.id)selectBox(box);$('boxForm').hidden=true;editingBox=null;revision++;sync();render();toast('箱・配送設定を保存しました')}}catch(e){$('boxError').textContent=e.message}};
$('boxList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.editBox||b.dataset.deleteBox,box=boxes.find(x=>x.id===id);if(!box)return;if(b.dataset.editBox)openBox(box);else confirmAction(`「${box.name}」を削除しますか？今回の入力金額と過去の計算履歴は残ります。`,()=>{const next=boxes.filter(x=>x.id!==id);if(localSave({boxes:next})){boxes=next;if(state.boxId===id)state.boxId='';renderBoxes();toast('箱・配送設定を削除しました')}})};
function renderAnalysis(){const ready=!!lastResult;$('analysisEmpty').hidden=ready;$('analysisContent').hidden=!ready;if(!ready)return;
 const s=state,variants=[['現在の条件',s],['合算料率の比較',{...s,model:'consultant',buffer:s.buffer??20}],['厳しめの条件',{...s,fx:s.fx*.95,fuel:(s.fuel??0)+10,returnRate:Math.max(s.returnRate??0,3)}]];
 $('scenarios').innerHTML=variants.map(([title,x])=>{const r=P.calc(x);return `<article class="scenario"><h3>${title}</h3><strong>${r.profit===null?jpy(r.net):jpy(r.profit)}</strong><p>${r.profit===null?'原価未入力のため、物流・輸入費控除後の残額':'仕入等を引いた利益'}${title==='厳しめの条件'?'。円換算レート −5%、燃油 ＋10 ポイント、損失率 3% 以上':''}</p></article>`}).join('');
 const value=r=>r.profit===null?jpy(r.net)+'（残額）':jpy(r.profit);
 $('fxChart').innerHTML=[-10,-5,0,5,10].map(d=>{const fx=s.fx+d;return fx>0?row(`1 USD = ${fx.toFixed(2)} 円`,value(P.calc({...s,fx}))):''}).join('');
 $('fuelTable').innerHTML='<h3>燃油サーチャージ</h3>'+[40,50,60,70,80].map(fuel=>row(fuel+'%',value(P.calc({...s,fuel})))).join('');
 $('feeTable').innerHTML='<h3>合算手数料（比較用）</h3>'+[14,16,18,20,22].map(buffer=>row(buffer+'%',value(P.calc({...s,model:'consultant',buffer})))).join('');
 const starter=P.calc({...s,model:'detail',fvf:13.6,threshold:7500,upper:2.35}),basic=P.calc({...s,model:'detail',fvf:12.7,threshold:2500,upper:2.35}),saving=starter.fees-basic.fees;
 const annual=s.billing==='year',a=annual?s.starterYear:s.starterMonth,b=annual?s.basicYear:s.basicMonth,diff=a!==null&&b!==null?(b-a)*(1+s.vat/100):null;
 $('storeCompare').innerHTML=row('1 注文で減る FVF 等',usd(saving))+row('月額差を回収する注文数',diff===null?'設定で月額を入力':saving>0?Math.max(0,Math.ceil(diff/saving))+' 件':'算出できません')+row('月間の削減額（月額差を控除）',s.monthlyOrders===null||diff===null?'設定で月間注文数を入力':usd(s.monthlyOrders*saving-diff));
 $('shippingTable').innerHTML=[29.99,49.99,99.99,199.99,299.99].map(price=>{const x={...s,price},ship=P.issues(x,'recommend').length?null:P.recommend(x,'buyerShipping'),r=ship===null?null:P.calc({...x,buyerShipping:ship});return `<tr><td>${usd(price)}</td><td>${usd(ship)}</td><td>${r?usd(r.revenue):'—'}</td><td>${r?jpy(r.profit):'—'}</td></tr>`}).join('');}
function snapshot(){return {id:uid(),at:new Date().toISOString(),engineVersion:'2.0',checked:'2026-09-28',inputs:{...state},result:P.calc(state)}}
function renderHistory(){$('historyCount').textContent=history.length;$('historyList').innerHTML=history.length?history.map(h=>`<article class="history-item"><div><h3>${esc(h.inputs.name||'名称未入力の商品')}</h3><p>${esc(new Date(h.at).toLocaleString('ja-JP'))} / 商品 ${usd(h.inputs.price)} / 利益 ${jpy(h.result.profit)}</p><p>計算バージョン ${esc(h.engineVersion)} / 為替 ${h.inputs.fx} 円</p></div><div class="actions"><button data-load-history="${esc(h.id)}">開く</button><button data-csv-history="${esc(h.id)}">CSV</button><button data-delete-history="${esc(h.id)}">削除</button></div></article>`).join(''):'<p class="empty">まだ計算を保存していません。</p>'}
$('saveHistory').onclick=()=>{if(!lastResult)return;if(history.length>=D.MAX_HISTORY){toast('履歴は 500 件までです。バックアップ後に不要な履歴を削除してください。');return}const next=[snapshot(),...history];if(localSave({history:next})){history=next;renderHistory();toast('当時の条件で計算を保存しました')}};
$('historyList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const h=history.find(x=>x.id===(b.dataset.loadHistory||b.dataset.csvHistory||b.dataset.deleteHistory));if(!h)return;if(b.dataset.loadHistory){state={...P.defaults,...h.inputs};updates.fxMode='manual';updates.manualFx=state.fx;revision++;sync();render();switchTab('calculator');toast('当時の入力条件を開きました。保存済み履歴は変更しません。')}else if(b.dataset.csvHistory)exportCSV(h);else confirmAction('この計算履歴を削除しますか？元に戻すには JSON のバックアップが必要です。',()=>{const next=history.filter(x=>x.id!==h.id);if(localSave({history:next})){history=next;renderHistory()}})};
function saveFile(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportCSV(h){const resultLabels=resultCSVLabels(),rows=[['区分','項目','値'],['情報','計算バージョン',h.engineVersion],['情報','保存日時',h.at],...Object.entries(h.inputs).map(([k,v])=>['入力',labels[k]||k,v??'未入力']),...Object.entries(h.result).map(([k,v])=>['結果',resultLabels[k]||k,v??'未計算'])];const cell=v=>{let text=String(v);if(/^\s*[=+@\t\r]/.test(text)||(/^\s*-/.test(text)&&!Number.isFinite(Number(text))))text="'"+text;return '"'+text.replace(/"/g,'""')+'"'};saveFile('\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'ebay-calculation-'+h.at.slice(0,10)+'.csv','text/csv;charset=utf-8')}
$('exportCSV').onclick=()=>{if(lastResult)exportCSV(snapshot())};
function exportJSON(kind){read();try{const data=D.documentData(state,commonFromState(),boxes,history,kind,updates),text=JSON.stringify(data);if(new TextEncoder().encode(text).length>D.MAX_BYTES)throw new Error('バックアップが 3 MB を超えています。');saveFile(text,'ebay-'+kind+'-'+R.day()+'.json','application/json')}catch(e){toast(e.message)}}
$('exportSettings').onclick=()=>exportJSON('settings');$('exportAll').onclick=()=>exportJSON('backup');
$('importButton').onclick=()=>{$('importFile').value='';$('importFile').click()};
$('importFile').onchange=async e=>{const file=e.target.files[0];pendingImport=null;$('importError').textContent='';if(!file)return;try{if(file.size>D.MAX_BYTES)throw new Error('3 MB 以下の JSON を選択してください。');const d=D.parse(await file.text());D.mergeHistory(history,d.history);pendingImport=d;$('importBoxMode').value='merge';$('importSummary').textContent=`設定・箱 ${d.boxes.length} 件・履歴 ${d.history.length} 件を読み込みます。為替：${d.updates.fxMode==='auto'?'自動':'手動'}。運費データ元：${d.updates.shippingUrl||'未設定'}。`;$('importDialog').showModal()}catch(e){$('importError').textContent=e.message+' 現在のデータは変更していません。'}};
$('cancelImport').onclick=()=>{pendingImport=null;$('importDialog').close()};$('importDialog').addEventListener('cancel',()=>pendingImport=null);
$('confirmImport').onclick=()=>{if(!pendingImport)return;try{const d=pendingImport,nextBoxes=$('importBoxMode').value==='replace'?d.boxes:D.mergeBoxes(boxes,d.boxes),nextHistory=D.mergeHistory(history,d.history);if(nextBoxes.length>D.MAX_BOXES)throw new Error('箱が 100 件を超えます。');if(!localSave({settings:d.settings,boxes:nextBoxes,history:nextHistory,updates:d.updates}))return;settings=d.settings;boxes=nextBoxes;history=nextHistory;updates=d.updates;state=d.current;revision++;pendingImport=null;$('importDialog').close();sync();render();renderHistory();switchTab('calculator');toast('設定・箱・履歴を読み込みました。自動更新は次回の起動時から行います。')}catch(e){$('importDialog').close();$('importError').textContent=e.message}};
function applySavedFX(){if(updates.fxMode==='auto'&&updates.fxCache){state.fx=updates.fxCache.rate;state.fxDate=updates.fxCache.date;state.fxSource='Frankfurter'}else if(updates.fxMode==='manual'&&updates.manualFx!==null){state.fx=updates.manualFx;state.fxSource='手入力';state.fxDate=''}}
function renderRateStatus(){const latest=updates.fxCache;$('fxStatus').textContent=state.fxSource==='入力例（実勢レートではありません）'?'入力例の為替を使用しています。実際の販売時は更新してください。':state.fxSource==='Frankfurter'?`参考為替：${state.fx} 円 / データ日 ${state.fxDate}。休日等は前の公表値になります。` :state.fxSource==='手入力'?'手入力の為替を使用中。自動取得に戻す場合は「設定」で変更してください。':updates.fxMode==='auto'?'参考為替を自動取得します。取得できない場合は手入力してください。':'為替レートを入力してください。';
 $('rateLog').innerHTML=updates.logs.length?updates.logs.slice(0,50).map(l=>`<div class="source"><strong>${l.type==='fx'?'為替':'運費'} / ${l.status==='success'?'取得済み':l.status==='manual'?'手入力':'取得失敗'}</strong><p>${esc(new Date(l.at).toLocaleString('ja-JP'))} — ${esc(l.message)}</p><p>${esc(l.source)}</p></div>`).join(''):'<p class="empty">まだ更新記録はありません。</p>';
 $('updateStatus').textContent=rateBusy?'更新しています…':updates.logs.length?updates.logs[0].message:'運費データ元を指定しない場合、運費は自動更新しません。';}
function logRate(type,status,message,source){updates.logs=[{at:new Date().toISOString(),type,status,message,source},...updates.logs].slice(0,400)}
$('saveUpdates').onclick=()=>{try{const next=R.validate({...updates,fxMode:$('fxMode').value,shippingUrl:$('shippingFeed').value.trim(),manualFx:$('fxMode').value==='manual'?state.fx:updates.manualFx});if(next.shippingUrl)R.url(next.shippingUrl,location.href);if(next.shippingUrl!==updates.shippingUrl)next.shippingCheckedDay='';if(localSave({updates:next})){updates=next;revision++;if(updates.fxMode==='manual')logRate('fx','manual',state.fx===null?'手動入力に変更しました。':`手動レート ${state.fx} 円を使用します。`,'手入力');localSave();renderRateStatus();toast('更新方法を保存しました')}}catch(e){toast(e.message)}};
async function refreshRates(force=false){if(rateBusy)return;rateBusy=true;renderRateStatus();const day=R.day(),rev=revision;
 if(updates.fxMode==='auto'&&(force||updates.fxCheckedDay!==day)){updates.fxCheckedDay=day;try{const rate=R.parseFX(await R.fetchJSON(R.FX_URL));if(revision===rev&&updates.fxMode==='auto'){updates.fxCache=rate;state.fx=rate.rate;state.fxDate=rate.date;state.fxSource='Frankfurter';$('fx').value=state.fx;logRate('fx','success',`1 USD = ${rate.rate} 円。データ日 ${rate.date}。`,R.FX_URL);}else logRate('fx','success',`取得値 ${rate.rate} 円（${rate.date}）。操作中の入力を優先し、適用しませんでした。`,R.FX_URL)}catch(e){logRate('fx','error','為替を更新できませんでした。前回の値を維持します。必要なら手入力してください。',R.FX_URL)}}
 const shippingUrl=updates.shippingUrl;
 if(shippingUrl&&(force||updates.shippingCheckedDay!==day)){updates.shippingCheckedDay=day;try{const url=R.url(shippingUrl,location.href),feed=R.parseShipping(await R.fetchJSON(url));if(revision===rev&&updates.shippingUrl===shippingUrl){const result=R.applyShipping(boxes,feed,url);if(result.matched===0)throw new Error('箱のキー・配送サービス・寸法・重量が一致する料金がありません。');boxes=result.boxes;if(state.boxId){const selected=boxes.find(b=>b.id===state.boxId);if(selected&&selected.rateDate===feed.date)selectBox(selected)}for(const b of result.boxes.filter(b=>b.rateDate===feed.date&&b.rateSource===url)){logRate('shipping','success',`${b.name} / ${b.carrier} / ${b.length}×${b.width}×${b.height} cm・${b.weight} kg / 基本 ${b.freight} 円・燃油 ${b.fuel}%・追加 ${b.surcharge} 円 / データ日 ${feed.date}。`,url);}renderBoxes();sync();}else logRate('shipping','error','設定が変更されたため、取得した運費は適用しませんでした。',shippingUrl)}catch(e){logRate('shipping','error','運費を更新できませんでした。前回の値を維持します。'+(e.message||''),shippingUrl)}}
 rateBusy=false;if(!storageUnreadable)localSave();render();}
$('refreshRates').onclick=()=>refreshRates(true);
function load(){try{const text=localStorage.getItem(storageKey);if(text){const d=D.parse(text);settings=d.settings;boxes=d.boxes;history=d.history;updates=d.updates;}else{const old=localStorage.getItem(legacyKey);if(old){const d=D.parse(old);settings=d.settings;history=d.history;updates=d.updates;$('storageStatus').textContent='旧版の共通設定・履歴を引き継ぎました。商品欄は空欄から始めます。';}}}catch(e){storageUnreadable=true;$('storageStatus').textContent='保存データを読み取れませんでした。元の保存データは残しています。';}state=P.blank(settings);applySavedFX()}
$('sourceList').innerHTML=sources.map(([type,title,body,url])=>`<section class="source"><span class="tag">${esc(type)}</span><h3>${esc(title)}</h3><p>${esc(body)}</p>${url?`<a href="${url}" target="_blank" rel="noopener">公式資料を開く</a>`:''}</section>`).join('');
const formulas=[['日本価格を保つ','基準の税抜価格 = 税込価格 ÷（1 ＋ 国内消費税率）','税込 / 税抜は選択できます。税抜価格を入力した場合はそのまま使います。'],['回収する金額','税抜の日本価格 × 数量 ×（1 ＋ 追加する余裕）＋ 追加費用','追加費用には、加算を選んだ場合の梱包・作業・固定費・想定損失を含みます。仕入原価は引く前の目標です。'],['購入原価として使う','税抜入力の場合の仕入原価 = 入力価格 ×（1 ＋ 国内消費税率）','実際に支払う税込額を仕入原価として使います。'],['購入者の支払額','商品価格 ＋ 購入者負担送料 ＋ Sales Tax','Sales Tax は購入者から徴収されますが、セラーの売上に含めません。'],['落札手数料 FVF','第 1 区分までの金額 × FVF ＋ 上限超過分 × 超過分の料率','通常、商品・送料・Sales Tax が手数料の計算基準です。注文固定費は別途加算します。'],['海外決済・広告・手数料消費税','計算基準 × 各料率 / 手数料消費税 =（FVF ＋ 固定費 ＋ 海外決済費 ＋ 広告費）× 消費税率','広告は広告経由の注文を想定。不要なら 0 で計算します。'],['為替・出金費','プラットフォーム手数料控除後の正の残高 × 為替・出金料率','概算です。実際の決済・換金サービスの条件に合わせてください。'],['関税と通関処理費','関税 = 申告価格 × 関税率 / 処理費 = 選んだ基準 × 処理料率','申告価格は商品価格・商品と送料の合計・手入力から選びます。MPF 等の固定費は別入力です。'],['配送費・容積重量','配送費 = 基本送料 ×（1 ＋ 燃油率）＋ 追加送料 / 容積重量 = 長さ × 幅 × 高さ ÷ 除数','課金参考重量は実重量と容積重量の大きい方です。寸法だけで送料を自動算出することはありません。'],['残額と利益','残額 =（税抜売上 − eBay 費用 − 為替費 − 輸入費）× USD/JPY − 配送費（円）','利益 = 残額 − 仕入単価 × 数量 − 梱包 − 作業 − 固定費 − 想定損失。'],['損失・利益率','想定損失 = 返品等の発生率 × 1 件の損失 / 利益率 = 利益 ÷（税抜売上 × 為替）','実際の原価が未入力のときは利益を計算しません。'],['価格・送料の逆算','目標の残額・利益額・利益率を満たす金額を、0.01 USD 単位で求めます。','売上全体にかかる費用・関税・運費を同時に反映します。単純な 20% 上乗せではありません。'],['概算モデル','eBay 合算費用 = 手数料の計算基準 × 概算料率','FVF・海外決済・広告・注文固定費・手数料消費税の個別計算を置き換えます。為替費・関税・配送費は別に計算します。'],['比較','為替・燃油・合算料率をそれぞれ変えて再計算 / ストア比較 = FVF 等の削減額 − 月額料金の差','現在条件・概算・厳しめ条件を比較できます。Basic の無料出品枠の価値は含めません。']];
$('formulaList').innerHTML=formulas.map(([title,formula,help])=>`<div class="formula"><h3>${title}</h3><code>${formula}</code><p class="help">${help}</p></div>`).join('');
load();sync();render();renderHistory();refreshRates();
const mc=document.modelContext;if(mc?.registerTool){try{Promise.resolve(mc.registerTool({name:'read_pricing_simulation',description:'現在の入力と価格試算を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('引数は不要です');return {inputs:{...state},result:lastResult,recommended:recommendation,missing:P.issues(state)}}})).catch(()=>{});}catch{}}
