'use strict';
const $=id=>document.getElementById(id), cfg=window.EBAY_PRICING_CONFIG||{};
const money=(v,code='USD')=>v==null?'—':new Intl.NumberFormat(code==='JPY'?'ja-JP':'en-US',{style:'currency',currency:code||'USD'}).format(v);
const usd=v=>money(v,last?.input?.currency||settings.currency||'USD');
const jpy=v=>v==null?'未計算':new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(v);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
const STORAGE='ebay-pricing-secure:v1';
const defaults={model:'consultant',plan:'starter',quantity:1,targetMode:'amount',target:2000,desiredProfit:null,marketUsage:'reference',referenceTaxMode:'gross',referenceTax:10,referenceUplift:0,referenceExtras:'ignore',wholesaleTaxRate:10,wholesaleTaxTreatment:'include',marketId:'us',marketName:'米国',currency:'USD',buyerShipping:56.83,buyerShipping2:null,buyerShipping3:null,buyerShippingAdditional:null,fx:150,boxId:'box-a',length:119,width:10,height:5,weight:1.2,divisor:4000,freight:3691.25,freight2:null,freight3:null,freightAdditional:null,fuel:60,surcharge:0,pack:150,handling:100,overhead:0,fvf:13.6,threshold:7500,upper:2.35,intlMode:'manual',previousMonthSales:null,intl:1.35,ad:2,vat:10,orderLow:.30,orderHigh:.40,orderThreshold:10,ebayConversion:0,payoneerFx:0,bankFx:0,fxFee:0,buffer:20,duty:12.5,processing:2.1,processingBase:'duty',importFixed:0,customsMode:'price',tax:0,returnRate:0,returnLoss:15000,billing:'year',monthlyOrders:null,starterYear:4.95,basicYear:21.95,starterMonth:7.95,basicMonth:27.95,aiEnabled:true};
const defaultBoxes=[{id:'box-a',name:'本山モデル・箱 A',carrier:'speedpak-fedex',length:119,width:10,height:5,weight:1.2,divisor:4000,freight:3691.25,freight2:null,freight3:null,freightAdditional:null,fuel:60,surcharge:0,buyerShipping:56.83,buyerShipping2:null,buyerShipping3:null,buyerShippingAdditional:null,pack:150},{id:'box-b',name:'本山モデル・箱 B',carrier:'speedpak-fedex',length:119,width:10,height:10,weight:1.2,divisor:4000,freight:4696.25,freight2:null,freight3:null,freightAdditional:null,fuel:60,surcharge:0,buyerShipping:null,buyerShipping2:null,buyerShipping3:null,buyerShippingAdditional:null,pack:150}];
const defaultMarkets=[{id:'us',name:'米国',currency:'USD',fx:150,duty:12.5,processing:2.1,processingBase:'duty',importFixed:0,customsMode:'price',tax:0,buyerShipping:56.83,buyerShipping2:null,buyerShipping3:null,buyerShippingAdditional:null}];
const defaultCategories=[{id:'shaft',name:'ゴルフシャフト',hts:'9506.39.00.60',duty:12.5,processing:2.1,defaultBoxId:'box-a',source:'コンサルタント試算'},{id:'grip',name:'ゴルフグリップ',hts:'',duty:null,processing:null,defaultBoxId:'',source:''},{id:'bag',name:'ゴルフバッグ',hts:'',duty:null,processing:null,defaultBoxId:'',source:''},{id:'sleeve',name:'スリーブ・アダプター',hts:'',duty:null,processing:null,defaultBoxId:'',source:''},{id:'head',name:'ゴルフクラブヘッド',hts:'',duty:null,processing:null,defaultBoxId:'',source:''},{id:'club',name:'完成クラブ',hts:'',duty:null,processing:null,defaultBoxId:'',source:''}];
let settings={...defaults},boxes=structuredClone(defaultBoxes),categories=structuredClone(defaultCategories),markets=structuredClone(defaultMarkets),history=[],product={name:'',category:'',pricingSource:'wholesale',sourcePrice:null,desiredProfit:null,sku:'',origin:'',hts:'',cost:null},last=null,controller=null,timer=null,editingBox=null,editingCategory=null,editingMarket=null,turnstileToken='',turnstileWidget=null,pendingCalculate=false,pendingAI=false;

const basicFields=[['quantity','同じ注文の商品数量','number'],['targetMode','問屋価格の目標','select',[['amount','1点あたり利益額'],['margin','注文の利益率']]],['target','通常の希望利益 / 利益率','number'],['marketUsage','楽天・Yahoo! の使い方','select',[['reference','日本の販売価格を保つ'],['purchase','購入原価として使う']]],['referenceTaxMode','楽天・Yahoo! の価格','select',[['gross','税込'],['net','税抜']]],['referenceTax','日本の消費税率 %','number'],['wholesaleTaxRate','問屋仕入の消費税率 %','number'],['wholesaleTaxTreatment','問屋仕入の消費税','select',[['include','原価に加える'],['refundable','還付等を見込み原価に加えない']]],['boxId','通常使う箱','box'],['buyerShipping','1個注文の購入者送料','number'],['fx','販売通貨 / JPY 為替','number'],['freight','1個注文の基本送料 JPY','number'],['fuel','想定 Fuel Surcharge %','number'],['surcharge','追加送料 JPY','number'],['pack','梱包資材費 JPY','number']];
const feeFields=[['model','計算モデル','select',[['consultant','提供資料の 20% 合算'],['detail','実費を内訳から計算']]],['plan','eBay Store','select',[['starter','Starter / ストアなし'],['basic','Basic 以上']]],['buffer','合算費用 %','number'],['fvf','FVF %','number'],['threshold','FVF 第1区分上限 USD','number'],['upper','上限超過分 FVF %','number'],['intlMode','海外決済費の決め方','select',[['manual','手入力'],['auto','前月売上から自動判定']]],['previousMonthSales','前月 eBay 売上 USD','number'],['intl','海外決済手数料 %','number'],['ad','広告費 %','number'],['vat','手数料の消費税 %','number'],['orderLow','小額注文固定費 USD','number'],['orderHigh','通常注文固定費 USD','number'],['ebayConversion','eBay Currency Conversion %','number'],['payoneerFx','Payoneer 為替費用 %','number'],['bankFx','銀行出金費用 %','number'],['fxFee','その他の換金費用 %','number']];
const taxFields=[['duty','関税率 %','number'],['processing','通関処理率 %','number'],['processingBase','通関処理の対象','select',[['duty','関税額'],['value','申告価格']]],['importFixed','MPF・輸入固定費 USD','number'],['customsMode','関税計算価格','select',[['price','商品価格'],['total','商品価格＋購入者送料']]],['tax','購入者 Sales Tax %','number'],['handling','国内作業費 JPY','number'],['overhead','固定費配分 JPY','number'],['returnRate','返品・損失率 %','number'],['returnLoss','1件の返品損失 JPY','number']];
const boxFields=[['name','箱の名前','text'],['carrier','配送サービス','select',[['speedpak-fedex','SpeedPAK via FedEx'],['speedpak-dhl','SpeedPAK via DHL'],['other','その他']]],['length','長さ cm','number'],['width','幅 cm','number'],['height','高さ cm','number'],['weight','1個の実重量 kg','number'],['divisor','容積重量の除数','number'],['freight','1個注文の基本送料 JPY','number'],['freight2','同梱2個の基本送料 JPY','number'],['freight3','同梱3個の基本送料 JPY','number'],['freightAdditional','4個目以降の追加送料 / 個 JPY','number'],['fuel','想定燃油率 %','number'],['surcharge','追加送料 JPY','number'],['buyerShipping','1個注文の購入者送料','number'],['buyerShipping2','同梱2個の購入者送料','number'],['buyerShipping3','同梱3個の購入者送料','number'],['buyerShippingAdditional','4個目以降の購入者追加送料 / 個','number'],['pack','梱包費 JPY','number']];
const categoryFields=[['name','分類名','text'],['hts','HTS','text'],['duty','関税率 %','number'],['processing','通関処理率 %','number'],['defaultBoxId','通常使う箱','box'],['source','情報の出所','text']];
const marketFields=[['name','市場名','text'],['currency','通貨コード（USD / CAD 等）','text'],['fx','1通貨あたりの円','number'],['duty','関税率 %','number'],['processing','通関処理率 %','number'],['processingBase','通関処理の対象','select',[['duty','関税額'],['value','申告価格']]],['importFixed','輸入固定費','number'],['customsMode','関税計算価格','select',[['price','商品価格'],['total','商品価格＋購入者送料']]],['tax','購入者側の税率 %','number'],['buyerShipping','1個注文の購入者送料','number'],['buyerShipping2','同梱2個の購入者送料','number'],['buyerShipping3','同梱3個の購入者送料','number'],['buyerShippingAdditional','4個目以降の購入者追加送料 / 個','number']];
function control([key,label,type,opts],prefix='s_'){let input;if(type==='select')input=`<select id="${prefix+key}">${opts.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`;else if(type==='box')input=`<select id="${prefix+key}"></select>`;else input=`<input id="${prefix+key}" type="${type}" ${type==='number'?'min="0" step="any"':''}>`;return `<label>${label}${input}</label>`}
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',4000)}
function setServerStatus(state,text){$('connectionStatus').textContent=text;$('serverDot').className='server-dot '+state}
function row(k,v,cls=''){return `<div class="row ${cls}"><span>${esc(k)}</span><strong>${v}</strong></div>`}
function save(){localStorage.setItem(STORAGE,JSON.stringify({version:2,settings,boxes,categories,markets,history}));$('storageStatus').textContent='設定・市場・分類・箱・履歴はこのブラウザに保存します。'}
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');if(raw&&[1,2].includes(raw.version)){settings={...defaults,...raw.settings};boxes=Array.isArray(raw.boxes)?raw.boxes:boxes;categories=Array.isArray(raw.categories)?raw.categories:categories;markets=Array.isArray(raw.markets)&&raw.markets.length?raw.markets:markets;history=Array.isArray(raw.history)?raw.history:[]}}catch{$('storageStatus').textContent='保存データを読み込めませんでした。JSON バックアップを確認してください。'}}
function switchTab(id){document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id))}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function renderSelects(){const current=$('category').value||product.category;$('category').innerHTML='<option value="">選択してください</option>'+categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');$('category').value=current;for(const id of ['s_boxId','b_defaultBoxId','c_defaultBoxId']){const el=$(id);if(!el)continue;const v=el.value;el.innerHTML='<option value="">指定しない</option>'+boxes.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');el.value=v}const market=$('market');if(market){const v=market.value||settings.marketId;market.innerHTML=markets.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}（${esc(m.currency)}）</option>`).join('');market.value=markets.some(m=>m.id===v)?v:markets[0]?.id||''}}
function syncSettings(){for(const [key,,type] of [...basicFields,...feeFields,...taxFields]){const el=$('s_'+key);if(el)el.value=settings[key]??''}$('aiEnabled').checked=settings.aiEnabled!==false;renderSelects()}
function readSettings(){for(const [key,,type] of [...basicFields,...feeFields,...taxFields]){const el=$('s_'+key);settings[key]=type==='number'?(el.value===''?null:Number(el.value)):el.value}settings.aiEnabled=$('aiEnabled').checked}
function applyBox(id){const b=boxes.find(x=>x.id===id);if(!b)return;for(const k of ['length','width','height','weight','divisor','freight','freight2','freight3','freightAdditional','fuel','surcharge','buyerShipping','buyerShipping2','buyerShipping3','buyerShippingAdditional','pack'])settings[k]=b[k]??null;settings.boxId=b.id;syncSettings()}
function applyMarketShipping(m){for(const k of ['buyerShipping','buyerShipping2','buyerShipping3','buyerShippingAdditional'])settings[k]=m?.[k]??null}
function applyCategory(id){const c=categories.find(x=>x.id===id);if(!c)return;product.hts=c.hts;if(c.defaultBoxId)applyBox(c.defaultBoxId);if(c.duty!=null)settings.duty=c.duty;if(c.processing!=null)settings.processing=c.processing;applyMarketShipping(markets.find(x=>x.id===settings.marketId));syncSettings()}
function applyMarket(id){const m=markets.find(x=>x.id===id);if(!m)return;for(const k of ['fx','duty','processing','processingBase','importFixed','customsMode','tax'])if(m[k]!=null)settings[k]=m[k];applyMarketShipping(m);const c=categories.find(x=>x.id===product.category);if(c?.duty!=null)settings.duty=c.duty;if(c?.processing!=null)settings.processing=c.processing;settings.marketId=m.id;settings.marketName=m.name;settings.currency=(m.currency||'USD').toUpperCase();syncSettings()}
function renderMasters(){renderSelects();$('marketList').innerHTML=markets.map(m=>`<article class="box-item"><div><h3>${esc(m.name)}</h3><p>${esc(m.currency)} / 1 ${esc(m.currency)} = ${m.fx??'未設定'}円 / 関税 ${m.duty??'未設定'}%</p></div><div class="actions"><button data-me="${esc(m.id)}">編集</button><button data-md="${esc(m.id)}" ${markets.length===1?'disabled':''}>削除</button></div></article>`).join('');$('categoryList').innerHTML=categories.map(c=>`<article class="box-item"><div><h3>${esc(c.name)}</h3><p>HTS ${esc(c.hts||'未設定')} / 関税 ${c.duty==null?'未設定':c.duty+'%'} / 通関 ${c.processing==null?'未設定':c.processing+'%'}</p></div><div class="actions"><button data-ce="${esc(c.id)}">編集</button><button data-cd="${esc(c.id)}">削除</button></div></article>`).join('');$('boxList').innerHTML=boxes.map(b=>`<article class="box-item"><div><h3>${esc(b.name)}</h3><p>${b.length} × ${b.width} × ${b.height} cm / 1個 ${jpy((b.freight||0)*(1+(b.fuel||0)/100)+(b.surcharge||0))}</p><p>同梱2個 ${b.freight2==null?'未設定':jpy(b.freight2*(1+(b.fuel||0)/100)+(b.surcharge||0))} / 3個 ${b.freight3==null?'未設定':jpy(b.freight3*(1+(b.fuel||0)/100)+(b.surcharge||0))}</p></div><div class="actions"><button data-be="${esc(b.id)}">編集</button><button data-bd="${esc(b.id)}">削除</button></div></article>`).join('')}
function productInput(){const market=product.pricingSource!=='wholesale';return {...settings,name:product.name,category:product.category,pricingSource:product.pricingSource,referencePrice:market?product.sourcePrice:null,cost:market?(product.cost??null):product.sourcePrice,desiredProfit:product.desiredProfit,sku:product.sku,origin:product.origin,hts:product.hts,referenceURL:'',price:null,customsValue:null,box:'custom',fxSource:'',fxDate:'',shippingSource:'',shippingDate:''}}
function readProduct(){for(const k of ['name','category','pricingSource','sku','origin','hts'])product[k]=$(k).value;for(const k of ['sourcePrice','cost','desiredProfit'])product[k]=$(k).value===''?null:Number($(k).value)}
function updateSource(){const market=$('pricingSource').value!=='wholesale';$('sourcePriceLabel').firstChild.textContent=market?'日本の商品価格':'問屋価格（税抜）';$('sourceHelp').textContent=market?'税込／税抜は設定で変更できます。問屋価格も入力すると実際の利益を表示します。':'入力額は税抜です。設定した日本の消費税を原価に加え、希望利益からおすすめ価格を逆算します。';$('cost').disabled=!market}
function schedule(){readProduct();updateSource();clearTimeout(timer);timer=setTimeout(calculate,280)}
async function calculate(){
 const input=productInput(),missing=[];
 if(!input.name)missing.push('商品名');if(!input.category)missing.push('商品種類');if(input.pricingSource==='wholesale'&&input.cost==null)missing.push('仕入原価');if(input.pricingSource!=='wholesale'&&input.referencePrice==null)missing.push('日本の商品価格');
 if(missing.length){last=null;clearResult('未入力：'+missing.join('・'));return}
 if(!cfg.apiUrl){clearResult('計算サービスを利用できません。');setServerStatus('error','未設定');return}
 if(cfg.turnstileSiteKey&&!turnstileToken){pendingCalculate=true;clearResult('確認が完了するまでお待ちください。');setServerStatus('pending','確認中');requestTurnstile();return}
 pendingCalculate=false;controller?.abort();controller=new AbortController();setServerStatus('pending','通信中');
 try{const res=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/calculate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input,turnstileToken}),signal:controller.signal});const data=await res.json();if(!res.ok)throw new Error(data.error||'計算できませんでした。');last={input:{...input,price:data.recommended},...data};renderResult();setServerStatus('online','正常');if(cfg.turnstileSiteKey&&window.turnstile){turnstileToken='';turnstile.reset()}}
 catch(e){if(e.name!=='AbortError'){last=null;clearResult(e.message);setServerStatus('error','接続エラー')}}
}
function clearResult(message){for(const id of ['recommended','buyerTotal','net','profit','margin','effectiveRate'])$(id).textContent='—';$('recommendHint').textContent=message;$('feeBreakdown').innerHTML='';$('breakdown').innerHTML='';$('saveHistory').disabled=true;$('exportCSV').disabled=true;$('aiCard').hidden=true}
function renderResult(){const d=last,r=d.result,i=d.input,code=i.currency||'USD';if(!r){clearResult((d.missing||[]).join('・'));return}$('recommended').textContent=money(d.recommended,code);$('recommendTitle').textContent=i.desiredProfit!=null?'希望利益を確保する eBay 1点価格':i.pricingSource==='wholesale'?'目標利益を含む eBay 1点価格':'同じ収益を残す eBay 1点価格';$('recommendHint').textContent=`${i.marketName||'販売先'}向け・${r.quantity}点。商品合計 ${money(r.itemTotal,code)}＋購入者送料 ${money(r.buyerShipping,code)}。`;$('buyerTotal').textContent=money(r.base,code);$('net').textContent=jpy(r.net);$('profit').textContent=r.profit==null?'問屋価格未入力':jpy(r.profit);$('margin').textContent=r.profit==null?'—':`${r.margin.toFixed(1)}% / 1点 ${jpy(r.perUnit)}`;const eff=r.revenue?(r.fees+r.fxCost)/r.revenue*100:0;$('effectiveRate').textContent=eff.toFixed(2)+'%';$('feeBreakdown').innerHTML=(i.model==='consultant'?row(`商品代金・購入者送料等への合算費用 ${i.buffer}%`,money(r.fvf,code)):row(`FVF ${i.fvf}%`,money(r.fvf,code))+row(`海外決済 ${r.intlRate}%`,money(r.intl,code))+row(`広告 ${i.ad}%`,money(r.ad,code))+row('注文固定費',money(r.order,code))+row('手数料消費税',money(r.vat,code)))+row(`換金・出金費 合計 ${r.fxRate}%`,money(r.fxCost,code))+row('合計',money(r.fees+r.fxCost,code),'total')+`<p class="help">送料・関税も回収したうえで利益が残るよう、必要な商品価格を逆算しています。</p>`;$('breakdown').innerHTML=row(`商品価格（${r.quantity}点）`,money(r.itemTotal,code))+row('購入者送料',money(r.buyerShipping,code))+row('購入者支払総額',money(r.base,code),'total')+row('eBay・決済費用','−'+money(r.fees+r.fxCost,code))+row('関税','−'+money(r.duty,code))+row('通関・輸入固定費','−'+money(r.processing+(i.importFixed||0),code))+row('海外配送費','−'+jpy(r.shipping))+row('物流・輸入費控除後',jpy(r.net),'total')+(r.purchaseTotal==null?row('問屋仕入','未入力'):row('問屋価格（税抜）','−'+jpy(r.purchaseNet))+row(`日本消費税 ${i.wholesaleTaxTreatment==='include'?i.wholesaleTaxRate+'%':'還付等を見込み除外'}`,'−'+jpy(r.purchaseTax))+row('税込仕入合計','−'+jpy(r.purchaseTotal)))+row('梱包・作業・固定費','−'+jpy((i.pack||0)+(i.handling||0)+(i.overhead||0)))+row('返品等の想定損失','−'+jpy(r.risk))+row('利益',jpy(r.profit),'total');$('scenarios').innerHTML=row('現在条件',jpy(r.profit??r.net))+row('厳しめ条件',jpy(d.analysis.strict.profit??d.analysis.strict.net));$('fxAnalysis').innerHTML=d.analysis.fx.map(x=>row(`1 ${code} = ${x.fx.toFixed(2)}円`,jpy(x.value))).join('');$('fuelAnalysis').innerHTML=d.analysis.fuel.map(x=>row(`${x.rate}%`,jpy(x.value))).join('');$('saveHistory').disabled=false;$('exportCSV').disabled=false;$('aiCard').hidden=settings.aiEnabled===false;$('aiExplanation').innerHTML='<p class="help">ボタンを押すと、計算結果と確認ポイントを初心者向けに説明します。</p>'}
function download(text,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCSV(item=last){const code=item.input.currency||'USD',rows=[['項目','値'],['商品名',item.input.name],['販売市場',item.input.marketName],['数量',item.result.quantity],[`おすすめ1点価格 ${code}`,item.recommended],[`購入者総額 ${code}`,item.result.base],[`eBay・決済費用 ${code}`,item.result.fees+item.result.fxCost],[`関税 ${code}`,item.result.duty],[`通関・輸入費 ${code}`,item.result.processing+(item.input.importFixed||0)],['問屋価格（税抜）JPY',item.result.purchaseNet??'未入力'],['日本消費税 JPY',item.result.purchaseTax??'未入力'],['配送費 JPY',item.result.shipping],['残額 JPY',item.result.net],['利益 JPY',item.result.profit??'未計算']];download('\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),'ebay-calculation.csv','text/csv')}
function renderHistory(){$('historyCount').textContent=history.length;$('historyList').innerHTML=history.length?history.map(h=>`<article class="history-item"><div><h3>${esc(h.input.name)}</h3><p>${esc(new Date(h.at).toLocaleString('ja-JP'))} / ${money(h.recommended,h.input.currency||'USD')} / ${h.result.quantity||1}点 / 利益 ${jpy(h.result.profit)}</p></div><div class="actions"><button data-hc="${h.id}">CSV</button><button data-hd="${h.id}">削除</button></div></article>`).join(''):'<p class="empty">まだ保存していません。</p>'}
function kindMeta(kind){return kind==='b'?{fields:boxFields,form:'boxForm',host:'boxFields',newButton:'newBox',cancel:'cancelBox',error:'boxError'}:kind==='c'?{fields:categoryFields,form:'categoryForm',host:'categoryFields',newButton:'newCategory',cancel:'cancelCategory',error:'categoryError'}:{fields:marketFields,form:'marketForm',host:'marketFields',newButton:'newMarket',cancel:'cancelMarket',error:'marketError'}}
function openForm(kind,item){const meta=kindMeta(kind),prefix=kind+'_',initial=kind==='m'&&!item?{processingBase:'duty',customsMode:'price',importFixed:0,tax:0}:item||{};if(kind==='b')editingBox=item?.id||null;else if(kind==='c')editingCategory=item?.id||null;else editingMarket=item?.id||null;$(meta.form).hidden=false;for(const [key] of meta.fields)$(prefix+key).value=initial[key]??''}
function setupForm(kind,fields){const meta=kindMeta(kind);$(meta.host).innerHTML=fields.map(f=>control(f,kind+'_')).join('');$(meta.newButton).onclick=()=>openForm(kind,null);$(meta.cancel).onclick=()=>{$(meta.form).hidden=true};$(meta.form).onsubmit=e=>{e.preventDefault();try{const id=kind==='b'?editingBox:kind==='c'?editingCategory:editingMarket,obj={id:id||uid()};for(const [key,,type] of fields){const v=$(kind+'_'+key).value;obj[key]=type==='number'?(v===''?null:Number(v)):v}if(!obj.name)throw new Error('名前を入力してください。');if(kind==='m'){obj.currency=(obj.currency||'').toUpperCase();if(!/^[A-Z]{3}$/.test(obj.currency))throw new Error('通貨コードは USD、CAD のような3文字で入力してください。');if(['fx','duty','processing','tax','buyerShipping'].some(k=>obj[k]===null))throw new Error('為替・関税・通関率・税率・購入者送料を入力してください。')}const list=kind==='b'?boxes:kind==='c'?categories:markets,next=id?list.map(x=>x.id===id?obj:x):[...list,obj];if(kind==='b')boxes=next;else if(kind==='c')categories=next;else markets=next;save();$(meta.form).hidden=true;renderMasters();syncSettings();toast('保存しました')}catch(err){$(meta.error).textContent=err.message}}}
function requestTurnstile(){if(window.turnstile&&turnstileWidget!=null){try{turnstile.execute(turnstileWidget)}catch{}}}
async function explainAI(){
 if(!last||settings.aiEnabled===false)return;
 if(cfg.turnstileSiteKey&&!turnstileToken){pendingAI=true;$('aiExplanation').innerHTML='<p class="help">確認中です。少しお待ちください。</p>';setServerStatus('pending','確認中');requestTurnstile();return}
 pendingAI=false;const button=$('aiExplain');button.disabled=true;button.textContent='説明を作成中…';$('aiExplanation').innerHTML='<p class="help">計算結果を確認しています。</p>';
 try{const res=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:last.input,turnstileToken})});const data=await res.json();if(!res.ok)throw new Error(data.error||'説明を作成できませんでした。');$('aiExplanation').innerHTML=String(data.explanation||'説明を利用できません。').split(/\n{2,}/).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('');if(data.exhausted)toast('AIの利用上限に達したため、基本説明を表示しました');setServerStatus('online','正常')}
 catch{$('aiExplanation').innerHTML='<p>AI説明を利用できません。上の計算結果と「計算の説明」を確認してください。</p>';setServerStatus('online','正常')}
 finally{button.disabled=false;button.textContent='この結果を説明';if(cfg.turnstileSiteKey&&window.turnstile){turnstileToken='';turnstile.reset(turnstileWidget)}}
}
function initTurnstile(){
 if(!cfg.turnstileSiteKey){setServerStatus('pending','確認中');return}
 const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;
 script.onload=()=>{turnstileWidget=turnstile.render('#turnstile',{sitekey:cfg.turnstileSiteKey,appearance:'interaction-only',execution:'execute',callback:t=>{turnstileToken=t;setServerStatus('online','正常');if(pendingAI)explainAI();else if(pendingCalculate)calculate()},'expired-callback':()=>{turnstileToken=''},'error-callback':()=>{turnstileToken='';setServerStatus('error','確認エラー')}});setServerStatus('online','正常')};
 script.onerror=()=>setServerStatus('error','確認エラー');document.head.append(script)
}

$('basicSettings').innerHTML=basicFields.map(f=>control(f)).join('');$('feeSettings').innerHTML=feeFields.map(f=>control(f)).join('');$('taxSettings').innerHTML=taxFields.map(f=>control(f)).join('');setupForm('b',boxFields);setupForm('c',categoryFields);setupForm('m',marketFields);
$('productForm').oninput=schedule;$('pricingSource').onchange=schedule;$('desiredProfit').oninput=schedule;$('market').onchange=()=>{applyMarket($('market').value);schedule()};$('category').onchange=()=>{readProduct();applyCategory(product.category);schedule()};$('s_boxId').onchange=()=>applyBox($('s_boxId').value);
$('saveSettings').onclick=()=>{readSettings();save();toast('設定を保存しました');if(settings.aiEnabled===false)$('aiCard').hidden=true;schedule()};
$('aiEnabled').onchange=()=>{settings.aiEnabled=$('aiEnabled').checked;save();if(last)$('aiCard').hidden=!settings.aiEnabled};$('aiExplain').onclick=explainAI;
$('clear').onclick=()=>{product={name:'',category:'',pricingSource:'wholesale',sourcePrice:null,desiredProfit:null,sku:'',origin:'',hts:'',cost:null};for(const k of Object.keys(product))if($(k))$(k).value='';updateSource();clearResult('商品を入力してください。')};
$('sample').onclick=()=>{product={name:'N.S.PRO MODUS³ Tour 115',category:'shaft',pricingSource:'yahoo',sourcePrice:6300,desiredProfit:null,sku:'',origin:'日本',hts:'9506.39.00.60',cost:4000};Object.assign(settings,{model:'consultant',buffer:20,marketUsage:'reference',referenceExtras:'ignore',wholesaleTaxRate:10,wholesaleTaxTreatment:'include',marketId:'us',marketName:'米国',currency:'USD',fx:150,duty:12.5,processing:2.1,boxId:'box-a'});applyBox('box-a');for(const k of Object.keys(product))if($(k))$(k).value=product[k]??'';syncSettings();updateSource();schedule()};
$('saveHistory').onclick=()=>{if(!last)return;history.unshift({...structuredClone(last),id:uid(),at:new Date().toISOString()});save();renderHistory();toast('計算条件と結果を保存しました')};$('exportCSV').onclick=()=>last&&exportCSV();
$('historyList').onclick=e=>{const b=e.target.closest('button'),h=history.find(x=>x.id===(b?.dataset.hc||b?.dataset.hd));if(!h)return;if(b.dataset.hc)exportCSV(h);else{history=history.filter(x=>x.id!==h.id);save();renderHistory()}};
$('marketList').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.me)openForm('m',markets.find(x=>x.id===b.dataset.me));if(b?.dataset.md&&markets.length>1){markets=markets.filter(x=>x.id!==b.dataset.md);if(settings.marketId===b.dataset.md)applyMarket(markets[0].id);save();renderMasters()}};$('categoryList').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.ce)openForm('c',categories.find(x=>x.id===b.dataset.ce));if(b?.dataset.cd){categories=categories.filter(x=>x.id!==b.dataset.cd);save();renderMasters()}};$('boxList').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.be)openForm('b',boxes.find(x=>x.id===b.dataset.be));if(b?.dataset.bd){boxes=boxes.filter(x=>x.id!==b.dataset.bd);save();renderMasters();syncSettings()}};
$('exportSettings').onclick=()=>download(JSON.stringify({version:2,settings,boxes,categories,markets,history:[]},null,2),'ebay-settings.json','application/json');$('exportAll').onclick=()=>download(JSON.stringify({version:2,settings,boxes,categories,markets,history},null,2),'ebay-backup.json','application/json');$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(![1,2].includes(d.version)||!d.settings||!Array.isArray(d.boxes)||!Array.isArray(d.categories)||!Array.isArray(d.history))throw new Error('対応するバックアップではありません。');settings={...defaults,...d.settings};boxes=d.boxes;categories=d.categories;markets=Array.isArray(d.markets)&&d.markets.length?d.markets:structuredClone(defaultMarkets);history=d.history;save();syncSettings();renderMasters();renderHistory();toast('読み込みました')}catch(err){$('importError').textContent=err.message}};
load();syncSettings();renderMasters();renderHistory();for(const k of Object.keys(product))if($(k))$(k).value=product[k]??'';updateSource();clearResult('商品を入力してください。');initTurnstile();if(!cfg.apiUrl)setServerStatus('error','未設定');
