(function(root){
'use strict';
const FX_URL='https://api.frankfurter.dev/v2/rates?base=USD&quotes=JPY';
const defaults={fxMode:'auto',shippingUrl:'',manualFx:null,fxCache:null,fxCheckedDay:'',shippingCheckedDay:'',logs:[]};
function day(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
function dateOK(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))}
function parseFX(value,today=day()){const row=Array.isArray(value)?value.find(x=>x.base==='USD'&&x.quote==='JPY'):null;if(!row||typeof row.rate!=='number'||!Number.isFinite(row.rate)||row.rate<=0||row.rate>10000||!dateOK(row.date)||row.date>today)throw new Error('為替の取得結果を確認できませんでした。');return {rate:row.rate,date:row.date,source:FX_URL}}
function url(value,base){const u=new URL(value,base);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||(u.protocol==='http:'&&!['127.0.0.1','localhost'].includes(u.hostname)))throw new Error('HTTPS の運費データ URL を指定してください。');return u.href}
function parseShipping(data,today=day()){if(!data||data.format!=='golf-shipping-rates'||data.version!==1||data.currency!=='JPY'||data.destination!=='US'||!dateOK(data.date)||data.date>today||!Array.isArray(data.rates)||data.rates.length>100)throw new Error('対応する運費データではありません。');const keys=new Set();const rates=data.rates.map(r=>{if(!r||typeof r.key!=='string'||!r.key||r.key.length>120||keys.has(r.key))throw new Error('運費キーが不正です。');keys.add(r.key);if(!['speedpak-fedex','speedpak-dhl','other'].includes(r.carrier))throw new Error('配送サービスが不正です。');const out={key:r.key,carrier:r.carrier};for(const k of ['length','width','height','weight','freight','fuel','surcharge']){if(typeof r[k]!=='number'||!Number.isFinite(r[k])||r[k]<0||r[k]>1e9||(['length','width','height','weight'].includes(k)&&r[k]===0))throw new Error('運費データの数値が不正です。');out[k]=r[k]}return out});return {date:data.date,rates}}
function applyShipping(boxes,feed,source){let changed=0;const next=boxes.map(b=>{const r=feed.rates.find(x=>x.key===b.rateKey);if(!r||r.carrier!==b.carrier||!['length','width','height','weight'].every(k=>r[k]===b[k]))return {...b};changed++;return {...b,freight:r.freight,fuel:r.fuel,surcharge:r.surcharge,rateDate:feed.date,rateSource:source}});return {boxes:next,matched:changed}}
async function fetchJSON(url,fetcher=fetch){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetcher(url,{signal:controller.signal,cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw new Error('データ元に接続できませんでした。');const text=await response.text();if(text.length>500000)throw new Error('取得データが大きすぎます。');return JSON.parse(text)}finally{clearTimeout(timeout)}}
function validate(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('更新設定が不正です。');const x={...defaults,...raw};if(!['auto','manual'].includes(x.fxMode)||typeof x.shippingUrl!=='string'||x.shippingUrl.length>1000)throw new Error('更新設定を確認してください。');if(x.shippingUrl&&/^(?:javascript|data|file):/i.test(x.shippingUrl))throw new Error('運費 URL が不正です。');if(x.manualFx!==null&&(typeof x.manualFx!=='number'||!Number.isFinite(x.manualFx)||x.manualFx<.01))throw new Error('手動為替が不正です。');if(x.fxCache!==null)x.fxCache=parseFX([{base:'USD',quote:'JPY',...x.fxCache}]);for(const k of ['fxCheckedDay','shippingCheckedDay'])if(x[k]!==''&&!dateOK(x[k]))throw new Error('更新日が不正です。');if(!Array.isArray(x.logs)||x.logs.length>400)throw new Error('更新履歴が多すぎます。');x.logs=x.logs.map(l=>{if(!l||typeof l.at!=='string'||!Number.isFinite(Date.parse(l.at))||!['fx','shipping'].includes(l.type)||!['success','error','manual'].includes(l.status)||typeof l.message!=='string'||l.message.length>1200||typeof l.source!=='string'||l.source.length>1000)throw new Error('更新履歴の形式が不正です。');return {at:l.at,type:l.type,status:l.status,message:l.message,source:l.source}});return {fxMode:x.fxMode,shippingUrl:x.shippingUrl,manualFx:x.manualFx,fxCache:x.fxCache,fxCheckedDay:x.fxCheckedDay,shippingCheckedDay:x.shippingCheckedDay,logs:x.logs}}
const api={FX_URL,defaults,day,parseFX,parseShipping,applyShipping,fetchJSON,url,validate};root.RateUpdates=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
